version: '3.2'
services:
  php:
    build:
      context: ./dev/php
      args:
        HOST_USER: ${USER}
        HOST_USER_ID: ${USER_ID}
    container_name: avsc-json-converter
    hostname: avsc-json-converter
    tty: true
    volumes:
      - ../:/var/www/html